name: Deploy

on:
  workflow_run:
    workflows:
      - Tests
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 設定私鑰，為了 SSH 連線進正式環境
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 設定 known_hosts，避免鑰確認指紋
      - run: echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 連線進正式環境，並且更新程式、函式庫、快取
      - run: ssh ${{ secrets.USER_HOST }} '
          cd /srv/2023ironman
          && git pull
          && composer install --optimize-autoloader --no-dev
          && php artisan config:cache
          && php artisan event:cache
          && php artisan route:cache
          && php artisan view:cache
          '
