name: Deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest
    steps:
      # 設定私鑰，為了 SSH 連線進正式環境
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 設定 known_hosts，避免鑰確認指紋
      - run: echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 連線進正式環境，並且更新程式
      - run: ssh ${{ secrets.USER_HOST }} 'cd /srv/2023ironman && git pull'
